# https://taskfile.dev

version: "3"

dotenv: ["taskfiles/.env"]

includes:
  docker:
    taskfile: taskfiles/taskfile-docker_{{OS}}.yml
    aliases: [d]
  project:
    taskfile: taskfiles/taskfile-project_{{OS}}.yml
    aliases: [p]
tasks:
  # ---------------------------------------- #
  # Default tasks
  # ---------------------------------------- #

  default:
    desc: Show this help message
    cmd: task --list-all
    silent: true
